version: 2
jobs:
  build:
    docker:
     - image: python:3.7
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time 5s
          command: date
      - run: ssh-keyscan -H 178.128.95.3 >> ~/.ssh/known_hosts
      - deploy:
          name: Deploy Master to Heroku
          branch: ["master"]
          command: |
            git push user@192.168.0.1:repository master

