version: 2
jobs:
  build:
    docker:
     - image: python:3.7
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time 5s
          command: date
      - run: ssh-keyscan -H 178.128.95.3 >> ~/.ssh/known_hosts
      - run:
          command: |
            if[ "${CIRCLE_BRANCH}" == "master" ]; then
              git push test@178.128.95.3:repository master
            fi

